# via https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DavidAnson/markdownlint-cli2-action@v11
      with:
        globs: |
          *.md
          !test/*.md